//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bce.Dnn.DNNModule2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowersDBEntities : DbContext
    {
        public FlowersDBEntities()
            : base("name=FlowersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_FlowerColor> Table_FlowerColor { get; set; }
        public virtual DbSet<Table_Flowers> Table_Flowers { get; set; }
        public virtual DbSet<Table_Order> Table_Order { get; set; }
        public virtual DbSet<Table_PackageColor> Table_PackageColor { get; set; }
        public virtual DbSet<Table_Packaging> Table_Packaging { get; set; }
    }
}
