//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bce.Dnn.DNNModule2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_PackageColor
    {
        public int PackageColorID { get; set; }
        public string PackageColorName { get; set; }
    }
}
